version: '3.8'
services:
  email_sender:
    container_name: go_mailer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SMTP_USERNAME=pwttd.document@gmail.com
      - SMTP_PASSWORD=lmfejwjhbonqcayx
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_FROM_ADDRESS=pwttd.document@gmail.com
      - BASIC_AUTH_USERNAME=hak
      - BASIC_AUTH_PASSWORD=hak
      - SMTP_FROM_NAME='TDMS - Technical Document Management System'
    networks:
      - backend
networks:
  backend:



